# Generated by Django 4.0.1 on 2022-01-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_list_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
