# Generated by Django 4.0.1 on 2022-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_alter_list_options_list_date_created_list_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='lists', to='app.Product'),
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lists', to='app.Tag'),
        ),
    ]
