# Generated by Django 4.0.1 on 2022-01-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_list_products_alter_list_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
    ]
