# Generated by Django 4.0.1 on 2022-01-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_list_item_quantity_remove_list_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='list',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='list',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='list',
            name='products',
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='items', to='app.Product'),
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='lists', to='app.Item'),
        ),
    ]
