# Generated by Django 4.0.1 on 2022-01-22 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_list_users_list_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user_list',
        ),
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
