# Generated by Django 4.0.1 on 2022-01-22 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_users_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='name',
            field=models.CharField(default='list item', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='list name', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='app.list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='products',
            field=models.ManyToManyField(related_name='items', to='app.Product'),
        ),
    ]
