# Generated by Django 4.0.1 on 2022-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_listitem_name_alter_list_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='app.Product'),
        ),
    ]
