# Generated by Django 4.0.1 on 2022-01-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_listitem_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='products',
            field=models.ManyToManyField(related_name='items', to='app.Product'),
        ),
    ]
