# Generated by Django 4.0.1 on 2022-01-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_product_categories_listitem_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default=1, max_length=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='products',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='listitem',
            name='choices',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.choices'),
            preserve_default=False,
        ),
    ]
