# Generated by Django 4.0.1 on 2022-01-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_product_categories_listitem_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='app.Product'),
        ),
    ]
