# Generated by Django 4.0.1 on 2022-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_choices_remove_listitem_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='status',
        ),
        migrations.AddField(
            model_name='choices',
            name='choice_options',
            field=models.CharField(choices=[('a', 'Produce'), ('b', 'Dairy'), ('c', 'Baked Goods'), ('d', 'Meat and Fish'), ('f', 'Snacks'), ('g', 'Alcohol'), ('h', 'Baby Care'), ('i', 'Canned Goods'), ('j', 'Dry Goods'), ('k', 'Sauces and Condiments'), ('l', 'Herbs and Spices'), ('m', 'Non-Alcoholic Beverages'), ('n', 'Household and Cleaning'), ('o', 'Health and Beauty'), ('p', 'Pet Care'), ('q', 'Frozen Goods')], default='Produce', max_length=2),
            preserve_default=False,
        ),
    ]
