# Generated by Django 4.0.1 on 2022-01-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_listitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='products',
        ),
    ]
