# Generated by Django 4.0.1 on 2022-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_listitem_categories_listitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='category',
        ),
        migrations.AddField(
            model_name='listitem',
            name='choices',
            field=models.CharField(choices=[('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('BAKED', 'Baked Goods'), ('MEAT', 'Meat and Fish'), ('SNACKS', 'Snacks'), ('ALCOHOL', 'Alcohol'), ('BABY', 'Baby Care'), ('CANNED', 'Canned Goods'), ('DRY', 'Dry Goods'), ('SAUCES', 'Sauces and  Condiments'), ('HERBS', 'Herbs and Spices'), ('BEVERAGES', 'Non-Alcoholic Beverages'), ('HOUSEHOLD', 'Household and Cleaning'), ('HEALTH', 'Health and Beauty'), ('PET', 'Pet Care')], default='Produce', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
