# Generated by Django 4.0.1 on 2022-01-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_listitem_category_listitem_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='lists', to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='choices',
            field=models.CharField(blank=True, choices=[('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('BAKED', 'Baked Goods'), ('MEAT', 'Meat and Fish'), ('SNACKS', 'Snacks'), ('ALCOHOL', 'Alcohol'), ('BABY', 'Baby Care'), ('CANNED', 'Canned Goods'), ('DRY', 'Dry Goods'), ('SAUCES', 'Sauces and  Condiments'), ('HERBS', 'Herbs and Spices'), ('BEVERAGES', 'Non-Alcoholic Beverages'), ('HOUSEHOLD', 'Household and Cleaning'), ('HEALTH', 'Health and Beauty'), ('PET', 'Pet Care')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='item_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
