# Generated by Django 4.0.1 on 2022-01-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_list_tags_alter_listitem_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
