# Generated by Django 4.0.1 on 2022-01-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_list_name_alter_listitem_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='choices',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
