# Generated by Django 4.0.1 on 2022-01-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_listitem_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='Produce', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lists', to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='choices',
            field=models.CharField(choices=[('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('BAKED', 'Baked Goods'), ('MEAT', 'Meat and Fish'), ('SNACKS', 'Snacks'), ('ALCOHOL', 'Alcohol'), ('BABY', 'Baby Care'), ('CANNED', 'Canned Goods'), ('DRY', 'Dry Goods'), ('SAUCES', 'Sauces and  Condiments'), ('HERBS', 'Herbs and Spices'), ('BEVERAGES', 'Non-Alcoholic Beverages'), ('HOUSEHOLD', 'Household and Cleaning'), ('HEALTH', 'Health and Beauty'), ('PET', 'Pet Care')], default='Produce', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='name',
            field=models.CharField(default='Cucumber.', max_length=250),
            preserve_default=False,
        ),
    ]
