# Generated by Django 4.0.1 on 2022-01-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_list_tags_alter_listitem_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Produce'), (2, 'Dairy'), (3, 'Baked Goods'), (4, 'Meat and Fish'), (5, 'Snacks'), (6, 'Alcohol'), (7, 'Baby Care'), (8, 'Canned Goods'), (9, 'Dry Goods'), (10, 'Sauces and Condiments'), (11, 'Herbs and Spices'), (12, 'Non-Alcoholic Beverages'), (13, 'Household and Cleaning'), (14, 'Health and Beauty'), (15, 'Pet Care'), (16, 'Frozen Goods')], default='Produce', max_length=42)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='lists', to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='choices',
            field=models.ForeignKey(default='Produce', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.choices'),
            preserve_default=False,
        ),
    ]
