# Generated by Django 4.0.1 on 2022-01-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_choices_alter_list_tags_alter_listitem_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='status',
            field=models.CharField(choices=[('1', 'Produce'), ('2', 'Dairy'), ('3', 'Baked Goods'), ('4', 'Meat and Fish'), ('5', 'Snacks'), ('6', 'Alcohol'), ('7', 'Baby Care'), ('8', 'Canned Goods'), ('9', 'Dry Goods'), ('10', 'Sauces and Condiments'), ('11', 'Herbs and Spices'), ('12', 'Non-Alcoholic Beverages'), ('13', 'Household and Cleaning'), ('14', 'Health and Beauty'), ('15', 'Pet Care'), ('16', 'Frozen Goods')], default='1', max_length=42),
        ),
    ]
